### ISSUE TITLE
Table 1 (for next quarterly update)

### ISSUE THREAD

**Issue by akristensen** [gbif/doc-private-sector-data-publishing#15]
New, but not publishing yet

https://www.gbif.org/publisher/9a408a2b-6bbb-4c95-80d9-0dce1fba1c00
https://www.gbif.org/publisher/3ca2ab24-7f53-458e-b4ad-6e88ea6d9628

https://www.gbif.org/publisher/d5ef14a1-5177-4547-9ce2-46d84a4214eb 
https://www.gbif.org/publisher/4d14137b-ce2c-4111-98a9-0078f5d53237 

| https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be[Bosques Naturales S.A.^] | Materials | Spain | 0 | 0 | 0
| https://www.gbif.org/publisher/bc4da2dc-7950-4859-81fc-f11efcf7aa57[Adani Green Energy Limited^] | Energy | India | 0 | 0 | 0
| https://www.gbif.org/publisher/df604473-66f0-444d-94c4-22795f268afe [AngloGold Ashanti Colombia S.A.S^] | Materials | Colombia | 0 | 0 | 0
| https://www.gbif.org/publisher/280435ee-61cf-4188-9230-7a5eab718a1b [MANEFAU CONSULTORIA E SERVIÇOS AMBIENTAIS^] | Consulting | | 0 | 0 | 0

**Comment by akristensen** [comment]
Checklist dataset
| https://www.gbif.org/publisher/db41c5c6-d34a-4d27-8ac9-0c8d085393f7[Concesión La Pintada S.A.S^] | Industrials | Colombia | 2 | 0 | 0

**Comment by kcopas** [comment]
[New dataset](https://www.gbif.org/dataset/ecb3c8f3-b015-435e-a025-5e0ae99f181c) from existing publisher, [Total](https://www.gbif.org/publisher/728e3362-3063-4a43-a6cf-71d61b50025b)

New publisher to watch: [Sierra Pacific](https://www.gbif.org/publisher/442b50e8-8741-4c50-b1c8-04e4f6ff3021)

**Comment by kcopas** [comment]
New from Norway: [Akvaplana-niva](https://www.gbif.org/publisher/620e3d31-d433-4154-9cf6-232a6a6b5e3f)

**Comment by kcopas** [comment]
[Ashanti Gold Colombia](https://www.gbif.org/publisher/df604473-66f0-444d-94c4-22795f268afe) (referenced above) has published its first datasets. 

Parent company Ashanti Gold is based in South Africa.

**Comment by kcopas** [comment]
small one, but interesting—it's from a Scottish surveying firm: [Nocturne Environmental Surveyors](https://www.gbif.org/dataset/8070160d-012b-41fc-80e1-3d6f41acc257) (GB)

**Comment by kcopas** [comment]
And another:
https://www.gbif.org/publisher/c5245889-c63d-48fa-ae4b-90ddd74f1d2d

**Comment by EstebanMH-SiB** [comment]
We have a new publisher EPM https://www.gbif.org/publisher/d42b7e5d-a3e5-4fc2-8b3d-105336d70898

**Comment by kcopas** [comment]
Pierre Fabre !
https://www.gbif.org/dataset/4e916dc3-010f-4e23-bbe2-50e04f38b7fc

**Comment by akristensen** [comment]
Updated and new issue for next update is created  For next Update fall 2021 #17
