### ISSUE TITLE
For next Update fall 2021

### ISSUE THREAD

**Issue by akristensen** [gbif/doc-private-sector-data-publishing#17]
Check : new but not yet publishing

https://www.gbif.org/publisher/3ca2ab24-7f53-458e-b4ad-6e88ea6d9628

https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be

https://www.gbif.org/publisher/bc4da2dc-7950-4859-81fc-f11efcf7aa57

https://www.gbif.org/publisher/280435ee-61cf-4188-9230-7a5eab718a1b

https://www.gbif.org/publisher/442b50e8-8741-4c50-b1c8-04e4f6ff3021

Datasets:

https://www.gbif.org/publisher/db41c5c6-d34a-4d27-8ac9-0c8d085393f7

**Comment by kcopas** [comment]
[Carsa Gold](https://www.gbif.org/publisher/4d14137b-ce2c-4111-98a9-0078f5d53237)
