### ISSUE TITLE
For next quarterly update September 2022

### ISSUE THREAD

**Issue by akristensen** [gbif/doc-private-sector-data-publishing#20]
Check : new but not yet publishing

https://www.gbif.org/publisher/3ca2ab24-7f53-458e-b4ad-6e88ea6d9628

https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be

https://www.gbif.org/publisher/bc4da2dc-7950-4859-81fc-f11efcf7aa57

https://www.gbif.org/publisher/280435ee-61cf-4188-9230-7a5eab718a1b

https://www.gbif.org/publisher/442b50e8-8741-4c50-b1c8-04e4f6ff3021

Datasets:

https://www.gbif.org/publisher/db41c5c6-d34a-4d27-8ac9-0c8d085393f7

**Comment by EstebanMH-SiB** [comment]
Hi, we have more publishers from the private sector for this update:

Awake Travel:https://www.gbif.org/publisher/83500190-21b6-445c-ab2c-c0565fc0afce 
Central Hidroeléctrica de Caldas S.A E.S.P:https://www.gbif.org/publisher/bbf93124-1cc2-4cac-a101-b4412dd04e2a
Mineros Aluvial S.A.S. BIC:https://www.gbif.org/publisher/54eb018e-54d8-49cc-b98b-37733bb70028

**Comment by kcopas** [comment]
Def some new data from [Total](https://www.gbif.org/dataset/search?publishing_org=728e3362-3063-4a43-a6cf-71d61b50025b) (existing publisher).

**Comment by akristensen** [comment]
Done and updated - next update Dec 2022

**Comment by kcopas** [comment]
When you have a minute (and feel like doing some math), I think there's some text and percentage calculations that still need updating, just above the table. 

Note that the old stats are included but commented out, to preserve the change log and enable us to show the trend someday some way…
