### ISSUE TITLE
For next quarterly update June 2023

### ISSUE THREAD

**Issue by akristensen** [gbif/doc-private-sector-data-publishing#22]
NEW 
Check on publishing status

https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be

https://www.gbif.org/publisher/bc4da2dc-7950-4859-81fc-f11efcf7aa57

https://www.gbif.org/publisher/280435ee-61cf-4188-9230-7a5eab718a1b

https://www.gbif.org/publisher/442b50e8-8741-4c50-b1c8-04e4f6ff3021

 [Companhia Águas de Joinville](https://www.gbif.org/publisher/39c2c387-6880-47fb-8e9b-75cdca2d918e): registered data publisher from Brazil

**Comment by kcopas** [comment]
Actually, all five of these came in before the end of Q1 2023, so they could be added anytime ;-) 

* [Lake Tanganyika Floating Health Clinic](https://www.gbif.org/publisher/b1670923-c90b-4420-be96-1db600ed2109): new data publisher from Democratic Republic of Congo
* [HBH Projekt spol. s r.o.,Kabátnikova 5,  602 00 Brno,ČR – organizačná zložka Slovensko](https://www.gbif.org/publisher/946b9adc-5ec0-4d76-a143-8bd43444415f): new data publisher from Czechia
* [Parex Resources Colombia - AG Sucursal](https://www.gbif.org/publisher/dbc07e15-c05b-4781-9ec3-59d331a9a4d8): new data publisher from Colombia (8 March 2023)
* [Veolia Colombia](https://www.gbif.org/publisher/04a12c74-4b26-4994-a51a-8b733a57318b): new data publisher from Colombia (8 March 2023)
* [Equinor](https://www.gbif.org/publisher/51818adb-2745-4201-9397-6d6dc433954f): new data publisher from Norway (24 March 2023)

#### Check on publishing status

- [ ] [Companhia Águas de Joinville](https://www.gbif.org/publisher/39c2c387-6880-47fb-8e9b-75cdca2d918e): registered data publisher from Brazil

**Comment by akristensen** [comment]
Super, thanks Kyle. They are now added....
