### ISSUE TITLE
Next quarterly update June 2023

### ISSUE THREAD

**Issue by akristensen** [gbif/doc-private-sector-data-publishing#24]
NEW
Check on publishing status

https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be

https://www.gbif.org/publisher/bc4da2dc-7950-4859-81fc-f11efcf7aa57

https://www.gbif.org/publisher/280435ee-61cf-4188-9230-7a5eab718a1b

https://www.gbif.org/publisher/442b50e8-8741-4c50-b1c8-04e4f6ff3021

[Companhia Águas de Joinville](https://www.gbif.org/publisher/39c2c387-6880-47fb-8e9b-75cdca2d918e): registered data publisher from Brazil

**Comment by kcopas** [comment]
Legacy data from a former Danish environmental consultancy:
https://www.gbif.org/dataset/72e23311-b65a-46d0-bc07-ff0a251b47e1

**Comment by kcopas** [comment]
Not sure whether the June update's been run, so here are a couple of outliers:

- [HBH Projekt](https://www.gbif.org/publisher/946b9adc-5ec0-4d76-a143-8bd43444415f), Slovakia !!
- [ECA Liquefaction](https://www.gbif.org/publisher/a9e317a3-eaac-482e-818f-5316162b7b6b), Mexico—first client coming in through Citibank with the goal of meeting the Equator Principles recommendation
- [Sky Kapital Europe](https://www.gbif.org/publisher/778c1b9c-3410-43d4-b1d1-d873e2d2e9a9), newly endorsed by France

**Comment by kcopas** [comment]
Interesting one here: [ENGIE](https://www.gbif.org/publisher/76c3443b-bf10-4fb6-a6e7-aeaa65be383c) de France
