### ISSUE TITLE
Next quarterly update September 2023

### ISSUE THREAD

**Issue by akristensen** [gbif/doc-private-sector-data-publishing#25]
NEW - Check on publishing status

https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be

https://www.gbif.org/publisher/bc4da2dc-7950-4859-81fc-f11efcf7aa57

https://www.gbif.org/publisher/280435ee-61cf-4188-9230-7a5eab718a1b

https://www.gbif.org/publisher/442b50e8-8741-4c50-b1c8-04e4f6ff3021

[Companhia Águas de Joinville](https://www.gbif.org/publisher/39c2c387-6880-47fb-8e9b-75cdca2d918e): registered data publisher from Brazil

[ECA Liquefaction](https://www.gbif.org/publisher/a9e317a3-eaac-482e-818f-5316162b7b6b), Mexico—first client coming in through Citibank with the goal of meeting the Equator Principles recommendation

[Sky Kapital Europe](https://www.gbif.org/publisher/778c1b9c-3410-43d4-b1d1-d873e2d2e9a9), newly endorsed by France

**Comment by kcopas** [comment]
[New Equinor dataset](https://www.gbif.org/dataset/c4383526-4b48-4655-a070-26df37cb1847)

**Comment by kcopas** [comment]
@jhnwllr @akristensen can I ask if it's possible for us to change the workflow and update the table in a Contentful page?

I'm realizing that it would be nice not to bury this ongoing update in the guide and send people instead to a standalone page in GBIF.org, something along the lines of what @javiesgm did with [this table](https://www.gbif.org/composition/4y6ndyH9emZfbybrz72XqL/bid-all-projects).

Afterward (post-GB30), I might suggest we capture the change over time captured in the earlier comments but roll back to the document submitted as a final project deliverable.

**Comment by javiesgm** [comment]
@kcopas, Daniel and Morten handled [the table](https://www.gbif.org/composition/4y6ndyH9emZfbybrz72XqL/bid-all-projects) adaptation. It might be a good idea to include Daniel in this conversation.

**Comment by kcopas** [comment]
Duly noted (cc @dnoesgaard): I see I also failed to disclose the location of [the table I'm proposing to move](https://docs.gbif.org/private-sector-data-publishing/2.0/en/#who-publishes-data-through-gbif)…

I presume we're about to run a new set of numbers for the new quarter.

**Comment by dnoesgaard** [comment]
@kcopas are you suggesting moving the table into a static, manually updated Contentful page? Or are you thinking of a new type of page/block that automatically updates?

First one is a two minute job—the other requires a bit more ;)

**Comment by kcopas** [comment]
I think it's closer to the former than the latter. John's running numbers on a quarterly basis.

**Comment by MattBlissett** [comment]
John has an open pull request to automate the generation of the table for this document, based on machine tags created in the registry. We just need a bit of UI work for the registry console.

There are API queries to populate the table, https://api.gbif.org/v1/organization?machineTagNamespace=privateSector.gbif.org (and the datasets those organizations publish) and https://api.gbif.org/v1/dataset?machineTagNamespace=privateSector.gbif.org

**Comment by dnoesgaard** [comment]
Ah. I don't think I'm needed here at all :)
