### ISSUE TITLE
Next quarterly update: EOY 2023

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-private-sector-data-publishing#27]
### Colombia

- [Autopistas de la Sabana S.A.S.](https://www.gbif.org/publisher/faac8464-7152-4ccf-8488-e3b1b2bae4c4)
- [Ecoplanet LTDA](https://www.gbif.org/publisher/4ded6adc-a9a0-41f6-b600-5cfccdd04802)
- [Grupo Prodeco](https://www.gbif.org/publisher/188fd36a-2d61-4f35-8b67-d5529efb0005)
- [Promotora Stoneville S.A.S.](https://www.gbif.org/publisher/362f8f7d-17fc-466a-8637-e25fdac17784)
- [Sepia Rov S.A.S.](https://www.gbif.org/publisher/b7eb680b-e7db-4b24-b6c0-c7b70bc98368)

### Panama

- [Enel Panamá](https://www.gbif.org/publisher/de659b55-79d4-4244-9bba-b0019b4f2876)

### Chile

- [SysmicroLab](https://www.gbif.org/publisher/88ce39c6-3a7a-42e7-b93e-ca12315ba363)

### Guatemala

- [Asociación Balam ONG](https://www.gbif.org/publisher/d4df37e5-bc20-4d77-828d-8bf1a8aebe74)

**Comment by akristensen** [comment]
+ https://www.gbif.org/dataset/c4383526-4b48-4655-a070-26df37cb1847
