### ISSUE TITLE
Next quarterly update March 2024

### ISSUE THREAD

**Issue by akristensen** [gbif/doc-private-sector-data-publishing#28]
NEW - Check on publishing status

https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be

https://www.gbif.org/publisher/bc4da2dc-7950-4859-81fc-f11efcf7aa57

https://www.gbif.org/publisher/280435ee-61cf-4188-9230-7a5eab718a1b

https://www.gbif.org/publisher/442b50e8-8741-4c50-b1c8-04e4f6ff3021

[Companhia Águas de Joinville](https://www.gbif.org/publisher/39c2c387-6880-47fb-8e9b-75cdca2d918e): registered data publisher from Brazil

[ECA Liquefaction](https://www.gbif.org/publisher/a9e317a3-eaac-482e-818f-5316162b7b6b), Mexico—first client coming in through Citibank with the goal of meeting the Equator Principles recommendation

[Sky Kapital Europe](https://www.gbif.org/publisher/778c1b9c-3410-43d4-b1d1-d873e2d2e9a9), newly endorsed by France

https://www.gbif.org/publisher/88ce39c6-3a7a-42e7-b93e-ca12315ba363

https://www.gbif.org/publisher/d4df37e5-bc20-4d77-828d-8bf1a8aebe74

**Comment by kcopas** [comment]
Note that despite registering as a publisher, data from ECA Liquifaction (above) is coming in via CONABIO. The easiest way to see the datasets is through [this list](https://www.gbif.org/dataset/search?q=eca*20liquefaction&publishing_org=ff90b050-c256-11db-b71b-b8a03c50a862), while you can explore the 22,000+ records [here](https://www.gbif.org/occurrence/taxonomy?dataset_key=761b9180-2dc4-4c9c-a097-d79b879e53bb&dataset_key=be501945-ef1e-4534-89f0-9df6507697ca&dataset_key=ff5b3f2e-4d8c-4c74-b506-244f782be654&dataset_key=13f7efa4-e019-4d55-b572-829b99588586&dataset_key=41ae9e71-8277-4037-a0a6-be34cec37efc&occurrence_status=present).

Would be good to accommodate this in the table, as it's likely our first data to come in via the Equator Principles—even though Citibank has pulled out of that group ([cf.](https://www.thebanker.com/Major-US-banks-back-out-of-the-Equator-Principles-1710330460)).

If we're going to make use of machine tags to simplify our process of generating numbers like this, these five (nominal) CONABIO datasets should get one.
cc: @jhnwllr @javiesgm @dnoesgaard
