### ISSUE TITLE
New additions for Table 1

### ISSUE THREAD

**Issue by kcopas** [gbif/doc-private-sector-data-publishing#6]
While we're not in a position to find these any other way than manually, I want to record and park some additions for the [table of private-sector data publishers](https://docs.gbif-uat.org/private-sector-data-publishing/2.0/en/#table-01).

From Colombia via Dairo:

+ Carbones del Cerrejón https://www.gbif.org/publisher/14fb9c57-68a5-4870-b434-5355df7a9c3c
+ Cerro Matoso S.A https://www.gbif.org/publisher/1a4f4e64-eb3d-42c3-a359-1be3869b3a20
+ Promigas S.A E.S.P https://www.gbif.org/publisher/dbc2ab56-d499-403c-8db5-c1a49cd0b75f
+ Compensation International Progress S.A. -Ciprogress Greenlife https://www.gbif.org/publisher/03a8bc52-9c2e-4aee-8dd7-9b4d279e4960

from Brazil via [@GBIF Dodo](https://twitter.com/)

+  Mineração Vale Verde do Brasil Ltda. https://www.gbif.org/dataset/d0a90634-21fb-4c76-9081-98bf3930ad7c
> NOTE: this dataset will be difficult to add to any publisher-based queries and routines, as SiBBr is listed as the publisher. I happened to notice the dataset title!

from Brazil via text search for `empresa`

+ CVRD Reserva Natural Vale https://www.gbif.org/publisher/c38fb00b-8564-406c-b05b-2720815a0bd0

**Comment by kcopas** [comment]
New dataset [here](https://doi.org/10.15472/wxv4wk), plus a spike in records from EDP to catch up to, at minimum.

@akristensen, maybe we could find the time for a quick update to the figures in [Table 1](https://docs.gbif-uat.org/private-sector-data-publishing/2.0/en/#table-01)…

**Comment by akristensen** [comment]
Sure @kcopas just book me in outlook, after 11 is best for me

**Comment by kcopas** [comment]
Additional publishers via GBIF Dodo and the registry (all Colombia):
+ [Aguas de Bogotá](https://www.gbif.org/publisher/6d1beb45-43bc-499a-85a0-f06f67e81591)
+ [Concesión La Pintada S.A.S](https://www.gbif.org/publisher/db41c5c6-d34a-4d27-8ac9-0c8d085393f7)
+ [Federación Nacional de Cacaoteros](https://www.gbif.org/publisher/37c1c493-782c-4f53-914d-b1f66cdcf61c)
+ [Grupo Energía Bogotá](https://www.gbif.org/publisher/2977895d-3ce2-4fb9-b62e-a775c8fd9304)

**Comment by kcopas** [comment]
Registered but not yet publishing:

+ [AngloGold Ashanti Colombia S.A.S](https://www.gbif.org/publisher/df604473-66f0-444d-94c4-22795f268afe) (Colombia)
+ [MANEFAU CONSULTORIA E SERVIÇOS AMBIENTAIS](https://www.gbif.org/publisher/280435ee-61cf-4188-9230-7a5eab718a1b0) (Brazil)

**Comment by dagendresen** [comment]
[Some Norwegian private sector companies ](https://docs.google.com/spreadsheets/d/1wT6yTZiFbivWgHoH1qFiKHOUBnZBJ8PVdtFSTrJgmF0/edit#gid=537372236)publishing through [Artskart](https://www.gbif.org/publisher/d3978a37-635a-4ae3-bb85-7b4d41bc0b88) ([one big dataset](https://www.gbif.org/dataset/b124e1e0-4755-430f-9eab-894f25a9b59c))
(and thus not independently registered in GBIF - yet)
* Akvaplan-niva ([approx 12 974 occurrences](https://www.gbif.org/occurrence/search?publishing_org=d3978a37-635a-4ae3-bb85-7b4d41bc0b88&recorded_by=Akvaplan&recorded_by=Akvaplan%20Niva&recorded_by=Akvaplan%20Niva%20AS&recorded_by=Akvaplan-NIVA~2FNIVA&recorded_by=Akvaplan-Niva&recorded_by=Akvaplan-Niva,%20station%201.&recorded_by=Akvaplan-Niva,%20station%2010.&advanced=1&occurrence_status=present)) - Consulting, Survey
** ([approx 29 384 including museum samples collected by](https://www.gbif.org/occurrence/search?recorded_by=Akvaplan&recorded_by=Akvaplan%20Niva&recorded_by=Akvaplan%20Niva%20AS&recorded_by=Akvaplan-NIVA~2FNIVA&recorded_by=Akvaplan-Niva&recorded_by=Akvaplan-Niva,%20station%201.&recorded_by=Akvaplan-Niva,%20station%2010.&advanced=1&occurrence_status=present))
* COWI AS ([approx 3 929 occurrences](https://www.gbif.org/occurrence/search?publishing_org=d3978a37-635a-4ae3-bb85-7b4d41bc0b88&recorded_by=COWI%20AS&recorded_by=COWI&advanced=1&occurrence_status=present)) - Consultancy, Engineering
* Miljøfaglig Utredning AS ([approx 36 442 occurrences](https://www.gbif.org/occurrence/search?q=Milj%C3%B8faglig%20Utredning&country=NO&publishing_org=d3978a37-635a-4ae3-bb85-7b4d41bc0b88&occurrence_status=present)) - Consultancy, Survey
* Natur og samfunn AS ([approx 146](https://www.gbif.org/occurrence/search?q=Natur%20og%20samfunn&country=NO&publishing_org=d3978a37-635a-4ae3-bb85-7b4d41bc0b88&recorded_by=Natur%20og%20Samfunn%20AS&advanced=1&occurrence_status=present
) NB! including validated by and not only reported by) - Consultancy, Survey

**Comment by CristinaVillaverde** [comment]
Three Spanish companies publishing records through GBIF:

- [Navantia, S.A](https://www.gbif.org/publisher/52bd9c22-340b-480d-b414-73db37cd9379): 3 datasets
- [SUEZ en España](https://www.gbif.org/publisher/ca11748e-a30a-4252-930f-bdb017e942c5): 1 dataset
- [LafargeHolcim Spain](https://www.gbif.org/publisher/2d7ea901-0128-4a7a-8207-425020c1fd99): 2 datasets
And registered but not yet publishing:
- [Bosques Naturales S.A](https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be)

**Comment by EstebanMH-SiB** [comment]
Additional publisher for Colombia:

- [Biotica Consultores Ltda](https://www.gbif.org/publisher/8e6bc843-c1b4-4b10-b546-881f06049004): 2 datasets with 499 and 329 occurrences.

**Comment by kcopas** [comment]
@jlegind flagged a new NL publisher (data added 2 Feb 2021): 

[Regelink Ecology & Landscape](https://www.gbif.org/publisher/815809f1-e6e6-44df-b3fd-b17a9d87eada)

Suggest we move any endorsed but not-yet-publishing organizations to a new issue for the next update when you've completed the actionable items here @akristensen—that way we can show progress and clear the decks for more later.

**Comment by kcopas** [comment]
Newly endorsed publisher from India, but no data as of yet, so they'll probably carry over:
* [Adani Green Energy Limited](https://www.gbif.org/publisher/bc4da2dc-7950-4859-81fc-f11efcf7aa57)

**Comment by kcopas** [comment]
@akristensen be sure to click through for updated totals on any of the new ones listed—see f.eks. the one added by @EstebanMH-SiB above, which has added a dataset since he commented.

**Comment by akristensen** [comment]
> Three Spanish companies publishing records through GBIF:
> 
> * [Navantia, S.A](https://www.gbif.org/publisher/52bd9c22-340b-480d-b414-73db37cd9379): 3 datasets
> * [SUEZ en España](https://www.gbif.org/publisher/ca11748e-a30a-4252-930f-bdb017e942c5): 1 dataset
> * [LafargeHolcim Spain](https://www.gbif.org/publisher/2d7ea901-0128-4a7a-8207-425020c1fd99): 2 datasets
>   And registered but not yet publishing:
> * [Bosques Naturales S.A](https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be)



> Three Spanish companies publishing records through GBIF:
> 
> * [Navantia, S.A](https://www.gbif.org/publisher/52bd9c22-340b-480d-b414-73db37cd9379): 3 datasets
> * [SUEZ en España](https://www.gbif.org/publisher/ca11748e-a30a-4252-930f-bdb017e942c5): 1 dataset
> * [LafargeHolcim Spain](https://www.gbif.org/publisher/2d7ea901-0128-4a7a-8207-425020c1fd99): 2 datasets
>   And registered but not yet publishing:
> * [Bosques Naturales S.A](https://www.gbif.org/publisher/f9f1b710-d975-4215-9940-bb702299e9be)

Hi @CristinaGBIF not sure what category BosquesNaturales would be, is it wrong if we call it Retail, from what I could see on their homepage it looks like they produce furniture among alot of other things, but also have programs to plant trees?

**Comment by CristinaVillaverde** [comment]
Hi @akristensen , not sure if Retail fits well. They grow wood and produce wood products. Lumber company?

**Comment by kcopas** [comment]
Just catching up to this (busy day—sorry). List this as Materials, please @akristensen.

**Comment by akristensen** [comment]
> Hi @akristensen , not sure if Retail fits well. They grow wood and produce wood products. Lumber company?

thanks will go with Kyle's Materials suggestion. 
Have a great day.

**Comment by kcopas** [comment]
Just fyi, my suggestion of Materials aligns with a standard corporate classification we're using to organize our private-sector outreach.

**Comment by akristensen** [comment]
> Just fyi, my suggestion of Materials aligns with a standard corporate classification we're using to organize our private-sector outreach.

Thanks Kyle, do we have a list with terms, yesterday I also "invented " Technology", but was really not sure I found it to be the right term for classification of Navantia, SA

**Comment by kcopas** [comment]
[Global Industry Classification Standard ](https://www.msci.com/gics), aka GICS
